### ISSUE TITLE
Issue with dynamic import()

### ISSUE THREAD

**Issue by Bijit-Mondal** [undecaf/vue-barcode-scanner#2]
ERROR in external "https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.12/dist/main.js"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

**Comment by undecaf** [comment]
Apparently you are using [barcode-detector-polyfill](https://github.com/undecaf/barcode-detector-polyfill).
A little more information about what your target environment is would be extremely helpful in dealing with this issue.

**Comment by Bijit-Mondal** [comment]
`import{ZBarSymbolType as e,ZBarConfigType as t,scanRGBABuffer as n,ZBarScanner as r}from"https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.12/dist/main.js";`
this in `barcode-detector-polyfill/dist/main.js` wasn't working and after I change it to
`import { ZBarSymbolType as e, ZBarConfigType as t, scanRGBABuffer as n, ZBarScanner as r} from '@undecaf/zbar-wasm';` 
it is working now
